call pathogen#infect()
call pathogen#helptags()

let python_highlight_all = 1
syntax on
filetype plugin indent on
set background=light
set number

" I have a habit of saving excessively and the swp files just annoy me. 
set nobackup
set noswapfile

set grepprg=grep\ -nH\ $*
let g:tex_flavor='latex'

" Easy way to exit edit mode
ino jj <esc>
cno jj <c-c>

" Rebind redo key
map <F7> :redo <CR>

" Macro to compile current LaTeX file.
map <F8> :call CompileFile() <CR>
function! CompileFile()
	let current_filetype = &filetype
	if current_filetype == 'tex'
		:!pdflatex -halt-on-error %:t
	endif	
	if current_filetype == 'python'
		:!python %:t
	endif
endfunction

function! ToggleSpellCheck()
	set spell!
	if &spell
		echo "Spellcheck ON"
	else
		echo "Spellcheck OFF"
	endif
endfunction

" Set the conditions for relative numbering
au FocusLost * :call SetNoRelative()
au FocusGained * :call SetRelative()
autocmd InsertEnter * :call SetNoRelative()
autocmd InsertLeave * :call SetRelative()

" At this point I always want numbers to be there.
"map <C-p> :call NumberToggle()<CR>
"function! NumberToggle()
"	if(&nu == 1)
"		call SetRelative()
"	else
"		call SetNoRelative()
"	endif	
"endfunc

function! SetRelative()
	set nu!
	set rnu
endfunc

function! SetNoRelative()
	set nornu
	set nu
endfunc

" Default is relative numbering.
call SetRelative()

" Space toggles method folding
nnoremap <space> za

" Easy tab navigation
map <C-t>j :tabc<cr>
map <C-t>h :tabp<cr>
map <C-t>l :tabn<cr>

" NERDTree configuration
map <C-r> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
let NERDTreeIgnore = ['\.pyc$']


" Syntastic navigation shortcuts 
let mapleader = ","
nmap <leader>h :lnext<CR>
nmap <leader>l :lprevious<CR>
function! ToggleErrors()
	let old_last_winnr = winnr('$')
	lclose
	if old_last_winnr == winnr('$')
		Errors
	endif
endfunction
nnoremap <leader>e :call ToggleErrors()<CR> 

" Rebind delete to have a no copy version.
nnoremap <leader>d "_d

" Toggle tagbar
nmap <leader>t :TagbarToggle<CR>

" Toggle indentation display
nmap <leader>i :IndentGuidesToggle<CR>
let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=black
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=darkgrey

" Limelight settings.
let g:limelight_conceal_ctermfg = 'gray'
function! ToggleFocusMode()
	Goyo
	Limelight!!
endfunction

" Toggle focus mode.
nmap <leader>f :call ToggleFocusMode()<CR>
let g:goyo_width = 85


" Toggle spell check in current file.
map <leader>b :call ToggleSpellCheck()<CR>
map <leader>g :GrammarousCheck<CR>
map <leader>n :GrammarousReset<CR>

" Shortcut for preferred PHP error checking. 
nmap <leader>s :!php -l %<CR>

" Syntastic error message supression.
let g:syntastic_quiet_messages = { 'regex': 'invalid-name\|missing-docstring\|ungrouped-imports\|wrong-import-order\|redefined-outer-name' }
let g:syntastic_python_pylint_args = '--rcfile=/Users/andrewszot/.pylintrc'

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

" More syntastic options.
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_python_checkers = ['pylint']

" Keep Syntastic in passive mode. 
let g:syntastic_mode_map = { 'mode': 'passive', 'active_filetypes': [],'passive_filetypes': [] }
nnoremap <C-w>E :SyntasticCheck<CR> :SyntasticToggleMode<CR>

" Vim closetag
let g:closetag_filenames = "*.html,*.xhtml,*.phtml, *.txt"

" CTRLP fuzzy finder
" Ignore what is in the gitignore
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
let g:ctrlp_map = '<c-f>'
let g:ctrlp_cmd = 'CtrlP'


"" Because I can't figure out my pasting situation.
set pastetoggle=<F2>
"""""""""""""""""""""""""""""""""""""""""""""""""""

autocmd BufNewFile,BufRead *.py call SetPythonOptions()
function SetPythonOptions()
	set tabstop=4
	set softtabstop=4
	set shiftwidth=4
	set expandtab
	set textwidth=79
	set autoindent
	set fileformat=unix
	set nospell
endfunction

"" Function to delete trailing whitespace
func! DeleteTrailingWS()
	exe "normal mz"
	%s/\s\+$//ge
	exe "normal `z"
endfunc

"""""""
"" All read, write, open settings are below here.
"""""""

"" Defaults
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set autoindent
set nospell


"" Delete trailing whitespace on python file save
autocmd BufWrite *.py :call DeleteTrailingWS()


" Options for Scala
autocmd BufNewFile,BufRead *.scala call SetScalaOptions()
function SetScalaOptions()
	set tabstop=2
	set softtabstop=2
	set shiftwidth=2
	set wrap
	set expandtab
	set autoindent
	set textwidth=79
  set wrapmargin=2
endfunction

" Options for LaTex
autocmd BufNewFile,BufRead *.tex call SetTexOptions()
function SetTexOptions()
	set tabstop=2
	set softtabstop=2
	set shiftwidth=2
	set expandtab
	set autoindent
	set textwidth=79
	set nospell
endfunction

" Options for full stack. 
autocmd BufNewFile,BufRead *.js,*.html,*.css,*.vue,*.php call SetWebOptions()
function SetWebOptions()
	set tabstop=2
	set softtabstop=2
	set shiftwidth=2
	set expandtab
	set autoindent
	set nospell
endfunction

" Options for C++,C, CUDA
autocmd BufNewFile,BufRead *.cpp,*.h,*.c,*.cu,*.cuh call SetCOptions()
function SetCOptions()
	set tabstop=2
	set softtabstop=2
	set shiftwidth=2
	set textwidth=79
	set expandtab
	set autoindent
	set fileformat=unix
	set nospell
endfunction

autocmd BufRead,BufNewFile *.txt call SetTextOptions()
function SetTextOptions()
	set tabstop=2
	set softtabstop=2
	set shiftwidth=2
	set textwidth=79
	set wrap
	set expandtab
	set autoindent
	set nospell
endfunction

autocmd BufRead,BufNewFile *.md call SetMdOptions()
function SetMdOptions()
	set tabstop=2
	set softtabstop=2
	set shiftwidth=2
	set textwidth=79
	set expandtab
	set autoindent
	set nospell
endfunction
