base_data_dir: "/srv/share/aszot3/gala"
proj_name: "habitat2"
wb_entity: "aszot"
add_env_vars:
  - "MAGNUM_LOG=quiet"
  - "HABITAT_SIM_LOG=quiet"
conda_env: "hab_source2"
slurm_ignore_nodes: []
add_all: "WB.ENTITY $WB_ENTITY WB.RUN_NAME $SLURM_ID WB.PROJECT_NAME $PROJECT_NAME CHECKPOINT_FOLDER $DATA_DIR/checkpoints/$SLURM_ID/ VIDEO_DIR $DATA_DIR/vids/$SLURM_ID/ LOG_FILE $DATA_DIR/logs/$SLURM_ID.log TENSORBOARD_DIR $DATA_DIR/tb/$SLURM_ID/"
proj_data:
  hab_eval: "TEST_EPISODE_COUNT 10 SENSORS \"('THIRD_RGB_SENSOR', 'HEAD_DEPTH_SENSOR')\" TASK_CONFIG.SIMULATOR.DEBUG_RENDER True TASK_CONFIG.SIMULATOR.AGENT_0.SENSORS \"('HEAD_DEPTH_SENSOR', 'THIRD_RGB_SENSOR')\""
  hab_eval_debug: "TEST_EPISODE_COUNT 1 SENSORS \"('THIRD_RGB_SENSOR', 'HEAD_DEPTH_SENSOR')\" TASK_CONFIG.SIMULATOR.DEBUG_RENDER True TASK_CONFIG.SIMULATOR.AGENT_0.SENSORS \"('HEAD_DEPTH_SENSOR', 'THIRD_RGB_SENSOR')\""
  hab_eval_rgb_debug: "TEST_EPISODE_COUNT 1 SENSORS \"('THIRD_RGB_SENSOR', 'HEAD_DEPTH_SENSOR', 'HEAD_RGB_SENSOR')\" TASK_CONFIG.SIMULATOR.DEBUG_RENDER True TASK_CONFIG.SIMULATOR.AGENT_0.SENSORS \"('HEAD_RGB_SENSOR', 'HEAD_DEPTH_SENSOR', 'THIRD_RGB_SENSOR')\""
  hab_eval_rgb: "TEST_EPISODE_COUNT 10 SENSORS \"('THIRD_RGB_SENSOR', 'HEAD_DEPTH_SENSOR', 'HEAD_RGB_SENSOR')\" TASK_CONFIG.SIMULATOR.DEBUG_RENDER True TASK_CONFIG.SIMULATOR.AGENT_0.SENSORS \"('HEAD_RGB_SENSOR', 'HEAD_DEPTH_SENSOR', 'THIRD_RGB_SENSOR')\""
  arm_cam: "SENSORS \"('ARM_DEPTH_SENSOR',)\" TASK_CONFIG.SIMULATOR.AGENT_0.SENSORS \"('ARM_DEPTH_SENSOR',)\" RL.POLICY.include_visual_keys \"('robot_arm_depth',)\" RL.GYM_OBS_KEYS \"('robot_arm_depth', 'obj_start_sensor', 'joint', 'is_holding', 'relative_resting_position')\""
  no_render: "VIDEO_OPTION \"()\""
  pick_only: "TASK_CONFIG.TASK.FILTER_NAV_TO_TASKS \"('pick',)\""
