base_data_dir: "data/"
proj_name: "hab2_more"
wb_entity: "aszot"
ckpt_cfg_key: "CHECKPOINT_FOLDER"
add_env_vars:
  - "MAGNUM_LOG=quiet"
  - "HABITAT_SIM_LOG=quiet"
proj_dat_add_env_vars:
  debug: "HABITAT_ENV_DEBUG=1"
  debug_eval: "HABITAT_ENV_DEBUG=1"
conda_env: "hablab"
slurm_ignore_nodes: []
add_all: "habitat_baselines.wb.entity=$WB_ENTITY habitat_baselines.wb.run_name=$SLURM_ID habitat_baselines.wb.project_name=$PROJECT_NAME habitat_baselines.checkpoint_folder=$DATA_DIR/checkpoints/$SLURM_ID/ habitat_baselines.video_dir=$DATA_DIR/vids/$SLURM_ID/ habitat_baselines.log_file=$DATA_DIR/logs/$SLURM_ID.log habitat_baselines.tensorboard_dir=$DATA_DIR/tb/$SLURM_ID/ habitat_baselines.writer_type=wb"
eval_sys:
  ckpt_load_k: "habitat_baselines.eval_ckpt_path_dir"
  ckpt_search_dir: "checkpoints"
  run_id_k: "habitat_baselines.wb.run_name"
  sep: "="
  add_eval_to_vals:
    - "habitat_baselines.checkpoint_folder"
    - "habitat_baselines.log_file"
    - "habitat_baselines.wb.run_name"
  change_vals:
    "--run-type": "eval"
proj_data:
  # Eval settings
  render: "habitat/simulator/agents@habitat.simulator.agents.main_agent=depth_head_agent_vis"
  eval: "habitat_baselines.writer_type tb habitat_baselines.num_environments 1 habitat_baselines.load_resume_state_config=False"
  norender: "habitat_baselines.eval.video_option=\"[]\""
  med_eval: "TEST_EPISODE_COUNT 100"

  # Debug settings.
  debug: "habitat_baselines.num_environments=1 habitat_baselines.writer_type=tb habitat_baselines.log_interval=1 habitat_baselines.rl.ppo.num_mini_batch=1 habitat_baselines.video_dir=$DATA_DIR/vids/debug/ habitat_baselines.trainer_name=ppo"

  # Dataset settings.
  minival: "habitat_baselines.eval.split=minival"
  train: "eval.split=train" # Evaluate on the train dataset.

  # Task settings
  rearrange: "BASE_TASK_CONFIG_PATH configs/tasks/rearrange/rearrange.yaml"

  # Skills
  place: "benchmark/rearrange=place"
  pick: "bfor the experiments the enchmark/rearrange=pick"
  nav: "benchmark/rearrange=nav_to_obj"
  opencab: "benchmark/rearrange=open_cab"
  openfridge: "benchmark/rearrange=open_fridge"

  # Train settings.
  noforce: "TASK_CONFIG.TASK.FORCE_TERMINATE.MAX_ACCUM_FORCE -1.0 TASK_CONFIG.TASK.FORCE_TERMINATE.MAX_INSTANT_FORCE -1.0"
  noend: "TASK_CONFIG.TASK.COMPOSITE_SUCCESS.MUST_CALL_STOP False"

  hab_eval_rgb: "TEST_EPISODE_COUNT 10 SENSORS \"('THIRD_RGB_SENSOR', 'HEAD_RGB_SENSOR')\" TASK_CONFIG.SIMULATOR.DEBUG_RENDER True TASK_CONFIG.SIMULATOR.AGENT_0.SENSORS \"('HEAD_RGB_SENSOR', 'THIRD_RGB_SENSOR')\""
  arm_cam: "SENSORS \"('ARM_DEPTH_SENSOR',)\" TASK_CONFIG.SIMULATOR.AGENT_0.SENSORS \"('ARM_DEPTH_SENSOR',)\" RL.POLICY.include_visual_keys \"('robot_arm_depth',)\" RL.GYM_OBS_KEYS \"('robot_arm_depth', 'obj_start_sensor', 'joint', 'is_holding', 'relative_resting_position')\""
  tb: "habitat_baselines.writer_type=tb"
slurm:
  large:
    c: 20
    constraint: volta32gb
    time: 2880
    partition: learnfair
    cpu_mem: "4GB"
  small:
    c: 20
    time: 2880
    partition: learnfair
    cpu_mem: "4GB"
