base_data_dir: "/checkpoint/andrewszot/rlt/"
# proj_name: "p-skill-transformer"
# wb_entity: "cvmlp-whoknowsss"
proj_name: "hab2_more"
wb_entity: "aszot"
proj_dat_add_env_vars:
  debug: "HABITAT_ENV_DEBUG=1"
  debug3: "HABITAT_ENV_DEBUG=1"
add_env_vars:
  - "MAGNUM_LOG=quiet"
  - "HABITAT_SIM_LOG=quiet"
conda_env: "hablabexp"
slurm_ignore_nodes: []
eval_sys:
  ckpt_load_k: "habitat_baselines.eval_ckpt_path_dir"
  ckpt_search_dir: "checkpoints"
  run_id_k: "habitat_baselines.wb.run_name"
  sep: "="
  add_eval_to_vals:
    - "habitat_baselines.checkpoint_folder"
    - "habitat_baselines.log_file"
    - "habitat_baselines.wb.run_name"
  change_vals:
    "--run-type": "eval"
add_all: "habitat_baselines.wb.entity=$WB_ENTITY habitat_baselines.wb.run_name=$SLURM_ID habitat_baselines.wb.project_name=$PROJECT_NAME habitat_baselines.checkpoint_folder=$DATA_DIR/checkpoints/$SLURM_ID/ habitat_baselines.video_dir=$DATA_DIR/vids/$SLURM_ID/ habitat_baselines.log_file=$DATA_DIR/logs/$SLURM_ID.log habitat_baselines.tensorboard_dir=$DATA_DIR/tb/$SLURM_ID/ habitat_baselines.writer_type=wb"
proj_data:
  # Eval
  render: "habitat/simulator/agents@habitat.simulator.agents.main_agent=depth_head_agent_vis habitat_baselines.num_environments=1"
  eval: "habitat_baselines.load_resume_state_config=False"

  # Debug
  debug: "habitat_baselines.num_environments=1 habitat_baselines.writer_type=tb habitat_baselines.log_interval=1 habitat_baselines.rl.ppo.num_mini_batch=1 habitat_baselines.video_dir=$DATA_DIR/vids/debug/ habitat_baselines.trainer_name=ppo"
  debug3: "habitat_baselines.num_environments=1 habitat_baselines.writer_type=tb habitat_baselines.log_interval=1 habitat_baselines.rl.ppo.num_mini_batch=1 habitat_baselines.video_dir=$DATA_DIR/vids/debug/ habitat_baselines.trainer_name=ppo habitat.dataset.split=minival"
  debug_multiproc: "habitat_baselines.writer_type=tb habitat_baselines.log_interval=1 habitat_baselines.rl.ppo.num_mini_batch=1 habitat_baselines.video_dir=$DATA_DIR/vids/debug/ habitat.dataset.split=minival"
  debug2: "habitat_baselines.num_environments=8 habitat_baselines.writer_type=tb habitat_baselines.log_interval=1 habitat_baselines.rl.ppo.num_mini_batch=1 habitat_baselines.video_dir=$DATA_DIR/vids/debug/ habitat.dataset.split=minival"
  tb: "habitat_baselines.writer_type=tb"

  # Eval settings
  no_render: "VIDEO_OPTION \"()\""

  # Dataset settings.
  minival: "EVAL.SPLIT 'minival'"
  train: "EVAL.SPLIT 'train'" # Evaluate on the train dataset.

  noforce: "TASK_CONFIG.TASK.FORCE_TERMINATE.MAX_ACCUM_FORCE -1.0 TASK_CONFIG.TASK.FORCE_TERMINATE.MAX_INSTANT_FORCE -1.0"
  noend: "habitat.task.measurements.composite_success.must_call_stop=False habitat.task.actions.rearrange_stop.should_stop=False"

  # Skills
  place: "BASE_TASK_CONFIG_PATH configs/tasks/rearrange/place.yaml"
  pick: "BASE_TASK_CONFIG_PATH configs/tasks/rearrange/pick.yaml"
  nav: "BASE_TASK_CONFIG_PATH configs/tasks/rearrange/nav_to_obj.yaml"
  opencab: "BASE_TASK_CONFIG_PATH configs/tasks/rearrange/open_cab.yaml"
  openfridge: "BASE_TASK_CONFIG_PATH configs/tasks/rearrange/open_fridge.yaml"
  rearrange: "BASE_TASK_CONFIG_PATH configs/tasks/rearrange/rearrange.yaml"
slurm:
  large:
    c: 10
    constraint: volta32gb
    time: 2880
    partition: learnfair
    cpu_mem: "4GB"
  small:
    c: 10
    time: 2880
    partition: learnfair
    cpu_mem: "4GB"
